title: Superman
author: Diexh
date: 2019-01-20
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  let try something fun

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
